### ISSUE TITLE
Utviklere har tilgang til delete deployment

### ISSUE THREAD

**Issue by linemos** [nais/tobac#2]
Noen utviklere har tilgang til å slette deployments direkte via kubectl i namespaces som er shared (ikke i default).

Eks:
```
$ kubectl delete deployment -n q0 -l app=soknaddagpenger-server
deployment.extensions "soknaddagpenger-server" deleted
```

**Comment by kimtore** [comment]
Dette skal forsåvidt være sånn... men team labels skal nå legges til grunn.

https://github.com/navikt/nais-yaml/commit/0c6c7579389604f29a751811acefc4343ab13e62
https://github.com/navikt/nais-yaml/commit/0f8987a8dca18a61240cf0a0cbe528669cd0cca1
